color:
  saturation: 0.4604269
  brandStrength: 0.7616192
  rhythmicContrast: 0.3736766
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.5569682
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.1989247
typography_spectrum: 0.4605735
name: Steve Light
