name: Steve Light
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4605735
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Steve Light - Wordpress Developer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FBFBF9'
    - '#D8B3A3'
    - '#150C15'
    - '#A48754'
    - '#654231'
  brandStrength: 0.7616192
  lightness: 0.5625
  saturation: 0.4604269
  rhythmicContrast: 0.5
purpose: []
